### ISSUE TITLE
Map config doesn't load

### ISSUE THREAD

**Issue by nlaha** [GCC-Minecraft-Team/sps-mc-link-spigot#18]
The new map system doesn't load configs properly.

**Comment by nlaha** [comment]
seems the maps are loading in onMap before the config has had a chance to populate the "maps" map.

**Comment by nlaha** [comment]
It also seems like onMap isn't being fired for all maps, if at all in some cases.

**Comment by nlaha** [comment]
Seems like we might not be able to use the onMap event. See the following example:
https://github.com/zDevelopers/ImageOnMap/blob/indev/src/main/java/fr/moribus/imageonmap/image/MapInitEvent.java

**Comment by nlaha** [comment]
fixed

**Comment by nlaha** [comment]
not fixed

**Comment by nlaha** [comment]
Temporary fix implemented, uses on player move so it's not ideal.

**Comment by 2kai2kai2** [comment]
Permanent fix by finding each registered map on startup and changing it.

Problem is that this uses the depreciated [`Server.getMap(int)`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.html#getMap(int)) method. In the future, this might be replaced if a better system can be found.
