### ISSUE TITLE
Player's can't unclaim some chunks

### ISSUE THREAD

**Issue by nlaha** [GCC-Minecraft-Team/sps-mc-link-spigot#26]
It seems to affect chunks that have been loaded after server restart.

**Comment by 2kai2kai2** [comment]
Maybe this is because the `HashMap.remove()` function uses .equals() which doesn't seem to always work for chunks.

**Comment by nlaha** [comment]
Yeah, I'll try comparing with .getX() and .getWorld()

**Comment by nlaha** [comment]
Seems that worked
