### ISSUE TITLE
Simplify claim commands

### ISSUE THREAD

**Issue by nlaha** [GCC-Minecraft-Team/sps-mc-link-spigot#3]
We need to simplify chunk claim commands, maybe something along the lines of:
/claim - claims a 3x3 square of chunks around the player
/unclaim - unclaims a 3x3 square of chunks around the player

**Comment by AnotexX** [comment]
I keep thinking of new QOL features for the claims plugin:
- /claim chunk -> Claims current chunk
- /claim chunk 3 -> add extra parameter at end to determine radius of claim
- /unclaim chunk -> unclaims current chunk
- /unclaim chunk 3 -> same as 2nd one
- if you do /claim in someone elses chunk it says "cant claim chunk, it is already claimed by : "player name" or it is a spawn chunk
- if you do /claim help, it gives you this list of info
- /claims -> tells you how many chunks you have claimed, how many more you can claim and how long until you have played enough to get another chunk
-
- /teamclaims -> tells you who has claims left in your team and how many
- /team add  "name" -> self explanatory
- /team remove "name - >self explanatory
- /team create -> self explanatory
- the teams and claims mod should be the same mod for easy compatibility between the two systems
- /team help -> gives you a list of all the teams commands (the ones below the gap in the list)
- we also need a plugin that makes one person sleeping skip the night,  so the entire server doesn't have to sleep at once
